analysis-paths:
- analysis
clean-targets:
- target
- dbt_packages
config-version: 2
data-paths:
- data
macro-paths:
- macros
model-paths:
- models
models:
  projet_stage_dbt:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table
name: projet_stage_dbt
profile: wwi_duckdb
snapshot-paths:
- snapshots
target-path: target
test-paths:
- tests
version: 1.0.0
